/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404/index.vue')['default']
    500: typeof import('./src/components/500/index.vue')['default']
    About: typeof import('./src/components/Setting/About.vue')['default']
    Account: typeof import('./src/components/Setting/Account.vue')['default']
    Advanced: typeof import('./src/components/Setting/Advanced.vue')['default']
    Button: typeof import('./src/components/HoverButton/Button.vue')['default']
    General: typeof import('./src/components/Setting/General.vue')['default']
    HoverButton: typeof import('./src/components/HoverButton/index.vue')['default']
    Invitation: typeof import('./src/components/Setting/Invitation.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    PromptStore: typeof import('./src/components/PromptStore/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar/index.vue')['default']
  }
}
